import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from "@/lib/utils";
import { getClassById } from "@/lib/firebase/admin/db/class";
import { AuthProvider } from "./auth-provider";
import { cookies, headers } from "next/headers";
import { UserClassProvider } from "./user-class-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const origin = headers().get("x-origin");
  const session = cookies().get("session");
  const loginResult = await fetch(`${origin}/api/auth/login`, {
    headers: {
      Cookie: `session=${session?.value}`,
    },
  });
  const loginResultData = await loginResult.json();
  const user = loginResultData.user;
  const userClass = user ? await getClassById(user.class_id) : null;

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <AuthProvider auth={user}>
          <UserClassProvider userClass={userClass}>
            {children}
          </UserClassProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
